### ISSUE TITLE
No donate link on front page

### ISSUE THREAD

**Issue by notmgsk** [magit/magit.vc#4]
Had to dig around different places on the web to find any donate page. I think it would be useful to have this on the front page of http://magit.vc

**Comment by tarsius** [comment]
I removed the link to https://magit.vc/donate and various direct links to some donation options when I lauched the Kickstarter campaign. Maybe I should restore those now? My intention was to do so once the Kickstarter campaign is over.

But yes it usually is a bit to hard to find out how to support a maintainer, which is why I have started https://github.com/tarsius/elisp-maintainers.

**Comment by tarsius** [comment]
The donation links are back.
